# -*- coding: utf-8 -*-
"""재활용쓰레기분류.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6FAp-5F1gpLkCrp6qtsxiRpJNiJu-3I
"""

# 1.1 필수 라이브러리 임포트
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import os
import shutil
import zipfile

# 1.2 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

# Colab 로컬 저장소로 복사하는 코드
source_dir = '/content/drive/MyDrive/garbage_classification'
destination_dir = '/content/garbage_data_local'
!cp -r "$source_dir" "$destination_dir"

# data_dir을 로컬 경로로 변경
data_dir = destination_dir

# 1.3 데이터 경로 설정

data_dir = '/content/drive/MyDrive/garbage_classification'

# 경로 확인
if not os.path.exists(data_dir):
    print(f"🚨 오류: 경로 '{data_dir}'에 폴더가 존재하지 않습니다. 경로를 다시 확인하고 수정하세요.")
else:
    print(f"데이터셋 학습 경로: {data_dir}")
    print(f"클래스 폴더 확인: {os.listdir(data_dir)}")

# 2. 데이터 전처리 (Preprocessing)
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# 2.1 하이퍼파라미터 설정
IMG_SIZE = 160
BATCH_SIZE = 32
SEED = 42


# 학습용 데이터 설정
train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,  # 필수 설정
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest',
    validation_split=0.2  # 20%를 검증용으로 분리
)

# 검증용 데이터 설정
val_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    validation_split=0.2
)`

# 2.3 데이터 로드 (제너레이터 생성)
print("--- 데이터 로드 및 분할 ---")

# 학습 데이터
train_generator = train_datagen.flow_from_directory(
    data_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='training',
    seed=SEED
)

# 검증 데이터
validation_generator = val_datagen.flow_from_directory(
    data_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    subset='validation',  # validation subset 지정
    seed=SEED
)

# 클래스 확인
print(f"클래스 맵핑: {train_generator.class_indices}")

#단순 CNN 학습
# 1. 모델 생성
bad_model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)),
    MaxPooling2D(2, 2),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Flatten(),
    Dense(512, activation='relu'),
    Dense(1, activation='sigmoid')
])

bad_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# 2. 데이터 증강 없이 원본 데이터로 학습
# (기존 train_generator 대신 증강 없는 버전 사용)
bad_train_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)
bad_train_generator = bad_train_datagen.flow_from_directory(
    data_dir, target_size=(150, 150), batch_size=32, class_mode='binary', subset='training', seed=42)
bad_validation_generator = bad_train_datagen.flow_from_directory(
    data_dir, target_size=(150, 150), batch_size=32, class_mode='binary', subset='validation', seed=42)

# 3. 학습 (10 Epoch)
print("--- CNN 그래프 생성용 학습 시작 ---")
bad_history = bad_model.fit(
    bad_train_generator,
    steps_per_epoch=len(bad_train_generator),
    epochs=10, # 금방 끝내기 위해 10번만
    validation_data=bad_validation_generator,
    validation_steps=len(bad_validation_generator)
)

# 4. 그래프 그리기
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(bad_history.history['accuracy'], label='Train Acc')
plt.plot(bad_history.history['val_accuracy'], label='Val Acc')
plt.title('Accuracy (Overfitting Example)')
plt.legend()
plt.subplot(1, 2, 2)
plt.plot(bad_history.history['loss'], label='Train Loss')
plt.plot(bad_history.history['val_loss'], label='Val Loss')
plt.title('Loss (Overfitting Example)')
plt.legend()
plt.show()

# 3. 딥러닝 모델 설계 (Transfer Learning)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, Input
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.optimizers import Adam

# 3.1 사전 학습된 모델 불러오기 (MobileNetV2)
base_model = MobileNetV2(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,  # 마지막 분류기 층은 제외
    weights='imagenet'
)

# 학습 속도를 높이고 과적합을 막기 위해 기본 모델의 가중치는 고정
base_model.trainable = False

# 3.2 새로운 모델 정의
model = Sequential([
    base_model,
    GlobalAveragePooling2D(), # 복잡한 연산을 줄여주는 풀링 층
    Dense(128, activation='relu'),
    Dropout(0.5),             # 과적합 방지
    Dense(1, activation='sigmoid') # 이진 분류 출력층
])

# 3.3 모델 컴파일
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print("\n--- 전이 학습 모델 구조 요약 ---")
model.summary()

# 4. 모델 학습 (Training) - 수정됨
from tensorflow.keras.callbacks import EarlyStopping

# 조기 종료 설정
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

EPOCHS = 20

print("\n--- 학습 시작 ---")

# len(generator)를 사용하면 배치 크기에 맞춰 스텝을 자동으로 계산해줍니다.
history = model.fit(
    train_generator,
    steps_per_epoch=len(train_generator),
    epochs=EPOCHS,
    validation_data=validation_generator,
    validation_steps=len(validation_generator),
    callbacks=[early_stopping]
)
print("\n--- 학습 완료 ---")

# 5. 성능 평가 및 시각화 (Evaluation)

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns  # 시각화를 위해 seaborn 추가
from sklearn.metrics import classification_report, confusion_matrix

# 5.1 학습 곡선 시각화
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(len(acc))

plt.figure(figsize=(12, 4))

# 정확도 그래프
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Train Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Accuracy Curve')

# 손실 그래프
plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Train Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Loss Curve')
plt.show()

# 5.2 최종 성능 리포트
print("\n--- 최종 모델 평가 ---")

# 검증 데이터셋을 사용하여 예측 수행 (셔플되지 않은 상태여야 함)
validation_generator.reset()
preds = model.predict(validation_generator, steps=len(validation_generator))

# 예측 확률을 0과 1로 변환 (0.5 기준)
y_pred = np.round(preds).astype(int).flatten()

# 실제 정답 가져오기
y_true = validation_generator.classes[:len(y_pred)]

# 분류 보고서 출력
print(classification_report(y_true, y_pred))

# 5.3 혼동 행렬 (Confusion Matrix) 시각화
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues') # fmt='d': 정수 형태로 출력
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

# 6. 결과 예측 시각화

def plot_predictions(generator, model, num_images=9):
    images, labels = next(generator)
    preds = model.predict(images)
    pred_labels = np.round(preds).astype(int).flatten()
    class_dict = {v: k for k, v in generator.class_indices.items()}

    plt.figure(figsize=(10, 10))
    for i in range(num_images):
        plt.subplot(3, 3, i + 1)
        plt.imshow(images[i])
        plt.axis('off')

        true_name = class_dict[int(labels[i])]
        pred_name = class_dict[pred_labels[i]]

        # 정답이면 파란색, 틀리면 빨간색 표시
        color = 'blue' if true_name == pred_name else 'red'
        plt.title(f"Actual: {true_name}\nPred: {pred_name}", color=color)
    plt.show()

print("\n--- 예측 결과 예시 ---")
validation_generator.reset()
plot_predictions(validation_generator, model)